<?php

namespace webrise1\mentor\models\scores;


use Yii;

/**
 * This is the model class for table "{{%team_task}}".
 *
 * @property int $task_id
 * @property int $team_id
 * @property int|null $point
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property Task $task
 * @property Team $team
 */
class TeamTask extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%mentor_team_task}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['task_id', 'team_id'], 'required'],
            [['task_id', 'team_id', 'point'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['task_id', 'team_id'], 'unique', 'targetAttribute' => ['task_id', 'team_id']],
            [['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::class, 'targetAttribute' => ['task_id' => 'id']],
            [['team_id'], 'exist', 'skipOnError' => true, 'targetClass' => Team::class, 'targetAttribute' => ['team_id' => 'id']],
        ];
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($this->isNewRecord || $changedAttributes['point'] != $this->point) {
            $this->team->reCount();
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $this->team->reCount();
        parent::afterDelete();
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'task_id' => 'Задание',
            'team_id' => 'Команда',
            'point' => 'Баллы',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Task]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTask()
    {
        return $this->hasOne(Task::class, ['id' => 'task_id']);
    }

    /**
     * Gets query for [[Team]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTeam()
    {
        return $this->hasOne(Team::class, ['id' => 'team_id']);
    }

    /**
     * @param int $teamId
     * @return false|int|null|string
     */
    public static function getAllTeamPoints(int $teamId)
    {
        return self::find()
            ->select('SUM([[point]]) as totalPoints')
            ->where(['team_id' => $teamId])
            ->scalar();
    }
}
