<?php
namespace webrise1\mentor\controllers\rbac;


use webrise1\mentor\models\rbac\URole;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use webrise1\mentor\models\User;
use Yii;

/**
 * Site controller
 */
class RuleController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if(!URole::checkUserAccess('RBAC'))
                   $this->redirect('/');
//        if ((!\Yii::$app->user->isGuest) && (\Yii::$app->user->identity->backend_status < User::BACKEND_STATUS_ADMINISTRATOR))
//        {
//          $this->redirect('/');
//        }
//
//        if (\Yii::$app->user->identity->backend_status == User::BACKEND_STATUS_MENTOR) {
//            $this->redirect('/mentor/');
//        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}